export const COUNTRY_LIST_REQUEST  = 'COUNTRY_LIST_REQUEST';
export const COUNTRY_LIST_SUCCESS  = 'COUNTRY_LIST_SUCCESS';
export const COUNTRY_LIST_FAIL     = 'COUNTRY_LIST_FAIL';

export const ACTIVITY_LIST_REQUEST  = 'ACTIVITY_LIST_REQUEST';
export const ACTIVITY_LIST_SUCCESS  = 'ACTIVITY_LIST_SUCCESS';
export const ACTIVITY_LIST_FAIL     = 'ACTIVITY_LIST_FAIL';

export const COUNTRY_DETAILS_REQUEST  = 'COUNTRY_DETAILS_REQUEST';
export const COUNTRY_DETAILS_SUCCESS  = 'COUNTRY_DETAILS_SUCCESS';
export const COUNTRY_DETAILS_FAIL     = 'COUNTRY_DETAILS_FAIL';

export const SEARCH_COUNTRY_REQUEST  = 'SEARCH_COUNTRY_REQUEST';
export const SEARCH_COUNTRY_SUCCESS  = 'SEARCH_COUNTRY_SUCCESS';
export const SEARCH_COUNTRY_FAIL     = 'SEARCH_COUNTRY_FAIL';

export const ACTIVITY_CREATE_REQUEST = 'ACTIVITY_CREATE_REQUEST'
export const ACTIVITY_CREATE_SUCCESS = 'ACTIVITY_CREATE_SUCCESS'
export const ACTIVITY_CREATE_FAIL = 'ACTIVITY_CREATE_FAIL'

export const ADD_COUNTRY  = 'ADD_COUNTRY';

export const FILTER_COUNTRY  = 'FILTER_COUNTRY';
